services:
  web:
    build: .
    command: bash -lc "sleep 5 && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/code
      - media:/data/media
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

  worker:
    build: .
    command: celery -A app.celery_app.celery_app worker -l info
    volumes:
      - ./:/code
      - media:/data/media
    env_file: .env
    depends_on:
      - redis
      - postgres

  beat:
    build: .
    command: celery -A app.celery_app.celery_app beat -l info
    volumes:
      - ./:/code
      - media:/data/media
    env_file: .env
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:16
    env_file: db.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
  media:
